### ISSUE TITLE
Dependency: ts-node

### ISSUE THREAD

**Issue by gingerbeardman** [shensven/Yadds#21]
- I also needed to install https://github.com/TypeStrong/ts-node

```
# Locally in your project.
npm install -D typescript
npm install -D ts-node
```

Cool project! I'll keep an eye on it. 

It would be nice if it supported responsive display for use on smart phones.

**Comment by shensven** [comment]
This project contains the TypeScript dependent.
https://github.com/shensven/Yadds/blob/44a2f0cc2c90193cec42a4ad859ee5916a8c60c2/package.json#L205-L206

The mobile version will be in development after the desktop version is released, maybe it will be a long time from now.

Thanks for your interest!

**Comment by gingerbeardman** [comment]
Interesting, this dependency was not picked up and installed automatically for me.
